language: node_js
node_js:
- 10
- 8
- 6
- 4
script:
- npm install
- npm test
deploy:
  provider: npm
  email: mail@geraintwhite.co.uk
  api_key:
    secure: jHEmH0RFt+x5HronUuLpf/of00B5rIjlOFlkB22iFfJOmIvRQGmiE8W+po2A3IFlh8EfBPYnyjoj8t2sdd1gcsJi/jhnfu2hnx6HDLlJ3PXYzHphQhdxka75Fprls2v5NrEQoOUKrGI+uKp2qPhA+z0L3qsWSoEvGJ/J9xLGJHypFQovx0m4A4lvoLLVZ6cHr0X7FgIXHuTsnGQgUcNAa1rTi5FBQrbeYeHkgFiD+dTyKBKE3z1le6ZJbOne+iJ5MqJ9ptMa4p+9PEJXNZ9Ejq39n1k+R7tpkuRmG/wFr7KyNVep+4rocko9vUUSyxd8UN+FJ3z+2zVjLFba1Ekh1Vb34dMykFCpbLguagnduRnc7DcImhoTMd3XFXVq1P1+nufQ7SaZgRIABgTPuH+Y2R6HftlvPRRYm/6m07nbBZSyIMHrY++82QXSdewBb47XvXvG5lN4XNPEfW0R7Rj4dWqvGWooSydrKLJ5F/Gcp0GEPcAvuP03sm0OeQwxcCw8bqIKm2QokQLyDXfLx7zY/t4yrU0aTkjOtOhUssgIMGQoVE5rgON1v8MdrVnXD2F/1Pd31QGMX8zzYg6n90G2ODTqJBXK2fhfJFBjZYXQ93OEyz2kxgoFXi65EWZ8BBDoOAhTLJ2L65ZYMxRyYUfUOL7R36ms3dmFAA+Aq3kzzVA=
  on:
    tags: true
    repo: grit96/gulp-md-template
