language: node_js

node_js:
  - '0.10'
  - '0.11'
  - '0.12'

script:
  - npm install
  - npm test

deploy:
  provider: npm
  email: mail@geraintwhite.co.uk
  api_key:
    secure: PUYnS43hVKlGnHq8gn8wXLXhy79A3JcCeZJlFyueGQBjWprKk9+g2iZ8Syy0b1+vH5hllTrxOEmuBs3RVnev7DZ91GfjS58B3DkiTu2R+tVg3hgVbcn1tOMToiODv5lRmrClCf51C6oovWtU6JzNVhNQyotx0H4VkLPhDWmuvfgUnwP6i3K5///iQE9Sn+3mUi8ISFgMBz3Qj35UXLGSkwmMlquB0tbnedVgKarVIdoDV9AoUF+u8mO9GuDAcQTDDSgpxjnb2JN72xgfmpuLrPx4Or5UOBvWtNxcNNKlXWdbn7JJfiGhdRBoeQzPJ2SvSWgteqvfvJZBRm0fJMExFR+AOAwXdOZhyY0uHMl3WD0fcApUNi+JtGwE6hh5KO0hcG63hCPC9GszRrOOQzpmGirQGwLKKfEbF78ZkqBPKlaLPyKGKZxoKCbZG6PQCuPJv+4EJRyl86Px6pD3sLFz2+yJQj8RCopxG2IM4BNsIxEOJ6FUtRSIrAyIcdZXQ0jKciiSBXLQ62V6ABt8FmTUnRsCvbog0/LYN61p7fWtYQg7ULOF7Kn7sJSPU4Cst+AqUe8+MoOARY5/yUYRAeghE2qLxOfllTwsSDwUFH4aRQXiXg/2pVltyvkinklcZoFpW6Km+++nlBjDMwnOSyT+dfjFvKmjXexA8VxmcxmFKco=
  on:
    tags: true
    repo: grit96/gulp-md-template
